COMPILE INSTRUCTIONS
====================

One can use the generated churn_lang.rb unless one desires to do modification to the language. Changes to the semantics of the language (objects) are in types.rb and the compilation logic is in churn_gen.rb.

NOTE: churn_lang.rb is a generated code from the TreeTop specification churn_lang.tt; changes should be made to churn_lang.tt only.

In order to generate a new version of churn_lang.rb, use the command:

	tt churn_lang.tt 
