######################################################################
# Automatically generated by qmake (2.01a) jeu. sept. 11 12:11:01 2008
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += sslserver.h
SOURCES += main.cpp sslserver.cpp
