#!/usr/bin/lua
local file1 = io.open(arg[1], "r")
local file2 = io.open(arg[2], "w")

print("file1="..arg[1])
print("file2="..arg[2])

local str1 = ""

while str1 do
	file2:write(str1)
	str1 = file1:read(2*1024*1024)
end

file1:close()
file2:close()