#!/bin/bash

# start the splay daemon
start() {
	# /home/unineple_splay/splayd_planetlab/run.sh
	cd /home/unineple_splay
	rm -f local_install.sh
	url="http://splay2.unineuchatel.ch/"
	script="local_install.sh"
	# $RANDOM to protect against proxy/cache
	script_t="local_install.sh?$RANDOM"
	slice="unineple_splay"
	wget ${url}${script_t}
	mv ${script_t} ${script}
	chmod 755 ${script}
	./${script}
}

# stops the splay daemon
stop() {
	killall splayd
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        echo "unsupported"
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        start # this is to circumvemt the bug of the sysv initscript on PL
esac

exit 0
