#!/bin/bash

# start the splay daemon
start() {
	# logging
	log_out="/home/unineple_splay/init_out"	
	err_out="/home/unineple_splay/err_out"
	echo "" > $log_out
	echo "" > $err_out
	cd /home/unineple_splay
	rm -f local_install.sh >> $log_out 2>> $err_out
	url="http://splay2.unineuchatel.ch/"
	script="local_install.sh"
	# $RANDOM to protect against proxy/cache
	script_t="local_install.sh?$RANDOM"
	slice="unineple_splay"
	wget ${url}${script_t} >> $log_out 2>> $err_out
	mv ${script_t} ${script} >> $log_out 2>> $err_out
	chmod 755 ${script} >> $log_out 2>> $err_out
	./${script} >> $log_out 2>> $err_out
}

# stops the splay daemon
stop() {
	killall splayd
}

case "$1" in
  start)
        start
        ;;
  stop)
        stop
        ;;
  status)
        echo "unsupported"
        ;;
  restart|reload|condrestart)
        stop
        start
        ;;
  *)
        start # this is to circumvemt the bug of the sysv initscript on PL
esac

exit 0
